### ISSUE TITLE
Base API path not considered

### ISSUE THREAD

**Issue by clamothe** [codecentric/hikaku#53]
# Setup information
**hikaku version: 3.1.2**
**specification converter: OpenAPI** 
**implementation converter: Spring MVC** 

# Describe the bug
Hikaku looks for the endpoint PUT `/{id}`. 

# Expected behavior
Hikaku will look for the endpoint PUT `/api/rest/v1/{id}`, prepending the base path of the server URL.
The OpenAPI Generator generator project uses the base path as the controller's `@RequestMapping` by default.

# Code samples
Can you provide specification snippets or code snippets?
```
openapi: 3.0.1
info:
  title: Badgr Pro APIs
  version: v1
servers:
- url: http://server.com/api/rest/v1
  description: API
paths:
  /{id}:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
                 type: string
      responses:
        200:
          description: success
```

**Comment by cc-jhr** [comment]
Hi @clamothe,

this is not a bug, but a design decision.
When we created hikaku we considered the endpoints to be the most important thing for equality checking. The data in the `Endpoint` is what we'd say defines an endpoint and what all implementations/specifications should support.
A base path seemed to be an entity itself and not part of the endpoint. As all the endpoints are only "prefixed" with it in the URL.
Since we didn't consider the base path to be a part of the endpoint itself, we decided to not support base paths. We are not supporting hostnames either.

**Comment by marcelstoer** [comment]
Just stumbled over this as well. The current behavior feels incorrect to me.

In OAS2/Swagger you have `basePath` + `path` that form the actual path. If you convert an OAS2 contract to OAS3 the old `basePath` value becomes `servers#url`. We use `basePath`/`servers#url` to denote the API major version encoded into the URL (e.g. `/v2`).

As the API major version is controlled by code rather than infrastructure - contrary to hostname, port, context root, etc. - it is part of our request mapping configuration. Hence, for the Spring MVC controllers we have code like this

```java
public static final String API_VERSION = "v2";
public static final String PATH_PREFIX = "/" + API_VERSION;

@RequestMapping(path = PATH_PREFIX + "/rules"...
public class RulesController {
```

Given your design decision now means we get this - effectively invalidating the entire API:

```
👀 Expected, but unable to find:
< GET /rules...
...
👻 Unexpected, but found:
< GET /v2/rules
...
```

That being said I wouldn't know what to do about the OP's case. There `servers#url` appears to be a "full" URL incl. hostname that is most likely not represented like that in the request mapping.

How about giving us the option to set a path/endpoint prefix in `HikakuConfig`? That way you could stand by your initial design decision but make hikaku usable for cases like mine and the OP's.
