### ISSUE TITLE
Regex error in regex replacement

### ISSUE THREAD

**Issue by mahieddine-ichir** [codecentric/hikaku#55]
# Setup information
**hikaku version:** `3.1.2`
**specification converter:** 
**implementation converter:** `SpringConverter` (in hikaku-spring)
**build tool and version:** `maven 3.x`
**test framework:** `junit 5.x`

# Describe the bug
I think the `removeRegex` method in `SpringConverter` has some issue on path patterns replacement, the regex does not work as expected.

# Expected behavior
When a path of the form `{resource:regex}`, example when `RequestMapping.value` is the format`/{sending_id:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}}`, the regex is not removed as expected and returns `/{sendings}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}}`, rather than `/{sendings}`.

# Suggestion
I think the regex should be replaced with

```
private fun removeRegex(path: String): String {
    if (path.contains(':')) {
        return path.replace(Regex(":.*"), "}")
    }

    return path
}
```

**Comment by cc-jhr** [comment]
Hello @mahieddine-ichir,

thank you very much for reporting this issue.
I took the regex you provided and created tests for this. As expected the tests failed. I then used your code suggestion and tested it against the extended test suite. All tests were successful. But then I thought about a case in which I could have something like: `/todos/{id:[0-9]+}/{title:[a-z]*}`. So I created a tests for this case as well. As expected this resulted in an error. So instead of creating a more complex regex I decided to split the path into segments and apply the simple regex on each segment.
